// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLNeoW2QOokFOIKGrS9hEnuDTAE0HrHv4',
    appId: '1:1084358002873:web:4d5b6a54bc6868e632f368',
    messagingSenderId: '1084358002873',
    projectId: 'quizzy-78b26',
    authDomain: 'quizzy-78b26.firebaseapp.com',
    storageBucket: 'quizzy-78b26.firebasestorage.app',
    measurementId: 'G-X27KCPX096',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn7exqapZ_RpvWytvZfDzLAod9FBOpoHc',
    appId: '1:1084358002873:android:355202a35cf86f9432f368',
    messagingSenderId: '1084358002873',
    projectId: 'quizzy-78b26',
    storageBucket: 'quizzy-78b26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ-RSGxgzMy2Bb_PpsfSMj91udoHuUpTc',
    appId: '1:1084358002873:ios:3ff1947126c36f3d32f368',
    messagingSenderId: '1084358002873',
    projectId: 'quizzy-78b26',
    storageBucket: 'quizzy-78b26.firebasestorage.app',
    iosBundleId: 'com.example.quizzyCrossPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ-RSGxgzMy2Bb_PpsfSMj91udoHuUpTc',
    appId: '1:1084358002873:ios:3ff1947126c36f3d32f368',
    messagingSenderId: '1084358002873',
    projectId: 'quizzy-78b26',
    storageBucket: 'quizzy-78b26.firebasestorage.app',
    iosBundleId: 'com.example.quizzyCrossPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLNeoW2QOokFOIKGrS9hEnuDTAE0HrHv4',
    appId: '1:1084358002873:web:038a736c9d6b06fb32f368',
    messagingSenderId: '1084358002873',
    projectId: 'quizzy-78b26',
    authDomain: 'quizzy-78b26.firebaseapp.com',
    storageBucket: 'quizzy-78b26.firebasestorage.app',
    measurementId: 'G-ZQFB7V6Q9B',
  );
}
